# Deployment Config
---
apiVersion: "apps/v1"
kind: "Deployment"
metadata:
  name: "APP_NAME"
  namespace: "default"
  labels:
    app: "APP_NAME"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: "APP_NAME"
  template:
    metadata:
      labels:
        app: "APP_NAME"
    spec:
      containers:
      - name: "APP_NAME-1"
        image: "IMAGE_NAME_URL"
---
apiVersion: "autoscaling/v2beta1"
kind: "HorizontalPodAutoscaler"
metadata:
  name: "APP_NAME-hpa-efsh"
  namespace: "default"
  labels:
    app: "APP_NAME"
spec:
  scaleTargetRef:
    kind: "Deployment"
    name: "APP_NAME"
    apiVersion: "apps/v1"
  minReplicas: 2
  maxReplicas: 2
  metrics:
  - type: "Resource"
    resource:
      name: "cpu"
      targetAverageUtilization: 80

---
apiVersion: v1
kind: Service
metadata:
  name: APP_NAME-service
spec:
  sessionAffinity: ClientIP
  type: LoadBalancer
  selector:
    app: APP_NAME
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8501
    - name: https
      protocol: TCP
      port: 443
      targetPort: 8501